import * as esbuild from "esbuild";
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");

const outDir = resolve(__dirname, "dist");
await mkdir(outDir, { recursive: true });

// ============================================================================
// Foundation 토큰 생성: foundation/*.css에서 --var 이름들을 추출해
// src/data/foundationTokens.generated.ts로 번들. 플러그인은 디스크 읽기 불가 →
// 빌드 타임 인라인 필요.
// ============================================================================
const foundationDir = resolve(__dirname, "foundation");
const generatedPath = resolve(__dirname, "src/data/foundationTokens.generated.ts");

async function generateFoundationTokens() {
  let files = [];
  try {
    files = (await readdir(foundationDir)).filter((f) => f.endsWith(".css"));
  } catch {
    // foundation 디렉토리 없으면 빈 export만 생성하고 skip
  }
  const rawByFile = {};
  const namesByFile = {};
  const allNames = new Set();
  for (const f of files) {
    const content = await readFile(resolve(foundationDir, f), "utf8");
    rawByFile[f] = content;
    const names = Array.from(content.matchAll(/--[a-zA-Z0-9_-]+(?=\s*:)/g)).map(
      (m) => m[0]
    );
    const unique = Array.from(new Set(names));
    namesByFile[f] = unique;
    for (const n of unique) allNames.add(n);
  }
  const out = `// GENERATED by esbuild.config.mjs — do not edit by hand.
export const FOUNDATION_CSS: Record<string, string> = ${JSON.stringify(
    rawByFile,
    null,
    2
  )};

export const FOUNDATION_TOKEN_NAMES_BY_FILE: Record<string, string[]> = ${JSON.stringify(
    namesByFile,
    null,
    2
  )};

export const FOUNDATION_TOKEN_NAMES: string[] = ${JSON.stringify(
    Array.from(allNames).sort(),
    null,
    2
  )};
`;
  await writeFile(generatedPath, out, "utf8");
  console.log(
    `[foundation] ${files.length} files, ${allNames.size} unique tokens → ${generatedPath}`
  );
}

await generateFoundationTokens();

const codeOptions = {
  entryPoints: [resolve(__dirname, "src/code.ts")],
  bundle: true,
  outfile: resolve(outDir, "code.js"),
  platform: "browser",
  target: "es2017",
  format: "iife",
  logLevel: "info"
};

const uiJsPath = resolve(outDir, ".ui.js");
const uiCssPath = resolve(outDir, ".ui.css");
const uiOptions = {
  entryPoints: [resolve(__dirname, "src/ui/main.tsx")],
  bundle: true,
  outfile: uiJsPath,
  platform: "browser",
  target: "es2017",
  format: "iife",
  jsx: "automatic",
  jsxImportSource: "preact",
  loader: { ".css": "css" },
  logLevel: "info"
};

async function emitUiHtml() {
  const htmlTemplate = await readFile(resolve(__dirname, "src/ui/index.html"), "utf8");
  const js = await readFile(uiJsPath, "utf8");
  let css = "";
  try {
    css = await readFile(uiCssPath, "utf8");
  } catch {
    // css is optional
  }
  const html = htmlTemplate
    .replace("<!-- INLINE_CSS -->", `<style>${css}</style>`)
    .replace("<!-- INLINE_JS -->", `<script>${js}</script>`);
  await writeFile(resolve(outDir, "ui.html"), html, "utf8");
  console.log("[ui] wrote dist/ui.html");
}

if (watch) {
  const codeCtx = await esbuild.context(codeOptions);
  const uiCtx = await esbuild.context({
    ...uiOptions,
    plugins: [
      {
        name: "emit-html",
        setup(build) {
          build.onEnd(async (result) => {
            if (result.errors.length === 0) await emitUiHtml();
          });
        }
      }
    ]
  });
  await codeCtx.watch();
  await uiCtx.watch();
  console.log("watching...");
} else {
  await esbuild.build(codeOptions);
  await esbuild.build(uiOptions);
  await emitUiHtml();
}
